### ISSUE TITLE
Cannot verify solutions 

### ISSUE THREAD

**Issue by Erwyn** [mikaelbr/bacon-love#20]
Hello there,

Here is what I get when trying to run the solutions:

```
/home/martin/.config/yarn/global/node_modules/bacon-love/verify.js:95
  return !!obj.onValue && !!obj.log;
              ^

TypeError: Cannot read property 'onValue' of undefined
    at isProbablyBaconInstance (/home/martin/.config/yarn/global/node_modules/bacon-love/verify.js:95:15)
    at run (/home/martin/.config/yarn/global/node_modules/bacon-love/verify.js:74:10)
    at Exercise.<anonymous> (/home/martin/.config/yarn/global/node_modules/bacon-love/verify.js:44:14)
    at next (/home/martin/.config/yarn/global/node_modules/workshopper-exercise/exercise.js:188:19)
    at /home/martin/.config/yarn/global/node_modules/workshopper-exercise/exercise.js:195:7
    at /home/martin/.config/yarn/global/node_modules/workshopper-exercise/execute.js:110:7
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

**Comment by mikaelbr** [comment]
Hey! It looks like you aren't returning a Bacon.js EventStream/Property? If you are, what versions are you using?

**Comment by Erwyn** [comment]
okay, my bad, I thought it was only about calling the Bacon method....

Sorry!
